import { defineConfig } from 'vitepress';

// three-box3d documentation site.
//
// IA (per docs/plan.md §Phase 4):
//   Getting Started → Concepts → Gotchas → API Reference → Examples
//
// The API Reference under /api is generated by TypeDoc (typedoc-plugin-markdown)
// into docs-site/api and is NOT committed — CI runs `npm run docs:api` before
// building the site. The sidebar links a stable landing page at /api/ that the
// TypeDoc run produces; locally, run `npm run docs:api` once so those pages exist.

const BASE = process.env.DOCS_BASE ?? '/';

export default defineConfig({
  base: BASE,
  lang: 'en-US',
  title: 'three-box3d',
  description: '3D physics for three.js, powered by box3d (Erin Catto).',
  cleanUrls: true,
  // TypeDoc output lands here after generation; don't fail the build if a dev
  // hasn't generated it yet.
  ignoreDeadLinks: true,
  head: [
    ['link', { rel: 'icon', href: 'data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 100 100%27%3E%3Ctext y=%27.9em%27 font-size=%2790%27%3E%F0%9F%A7%B1%3C/text%3E%3C/svg%3E' }],
    ['meta', { name: 'theme-color', content: '#ffb85a' }],
  ],
  themeConfig: {
    logo: undefined,
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Concepts', link: '/concepts/architecture' },
      { text: 'Gotchas', link: '/guide/gotchas' },
      { text: 'API', link: '/api/' },
      { text: 'Examples', link: '/guide/examples' },
      {
        text: 'v0.1',
        items: [
          { text: 'Releases', link: 'https://github.com/swapp1990/three-box3d/releases' },
          { text: 'npm: box3d-web', link: 'https://www.npmjs.com/package/box3d-web' },
          { text: 'npm: three-box3d', link: 'https://www.npmjs.com/package/three-box3d' },
          { text: 'npm: r3f-box3d', link: 'https://www.npmjs.com/package/r3f-box3d' },
        ],
      },
    ],
    sidebar: {
      '/guide/': [
        {
          text: 'Getting Started',
          items: [
            { text: 'Introduction', link: '/guide/' },
            { text: 'Installation & Quickstart', link: '/guide/getting-started' },
            { text: 'Bundler notes', link: '/guide/bundlers' },
            { text: 'Gotchas', link: '/guide/gotchas' },
            { text: 'Examples', link: '/guide/examples' },
          ],
        },
      ],
      '/concepts/': [
        {
          text: 'Concepts',
          items: [
            { text: 'Architecture', link: '/concepts/architecture' },
            { text: 'Worlds, handles & buffers', link: '/concepts/handles-and-buffers' },
            { text: 'The fixed step', link: '/concepts/fixed-step' },
            { text: 'Island sleeping', link: '/concepts/sleeping' },
            { text: 'Determinism', link: '/concepts/determinism' },
          ],
        },
      ],
    },
    socialLinks: [{ icon: 'github', link: 'https://github.com/swapp1990/three-box3d' }],
    footer: {
      message:
        'MIT Licensed. Wraps <a href="https://github.com/erincatto/box3d">box3d</a> (Erin Catto) — not affiliated with or endorsed by the box3d project.',
      copyright: 'Copyright © 2026 Swapnil Sawant',
    },
    search: { provider: 'local' },
    outline: { level: [2, 3] },
  },
});
